# Generated by Django 5.2.4 on 2025-08-04 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0008_alter_userinfo_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Estimated number of days', null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Completion percentage')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('designing_phase', 'Designing Phase'), ('awaiting_approval', 'Awaiting Approval'), ('under_construction', 'Under Construction'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=50)),
                ('plot_size', models.CharField(blank=True, max_length=50)),
                ('house_type', models.CharField(blank=True, choices=[('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('villa', 'Villa'), ('independent_floor', 'Independent Floor'), ('flat', 'Modern Flat')], max_length=50)),
                ('num_floors', models.CharField(blank=True, max_length=10)),
                ('basement', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('parking_required', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('covered', 'Covered Parking'), ('open', 'Open Parking')], max_length=20)),
                ('bedrooms', models.CharField(blank=True, choices=[('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4+', '4+ BHK')], max_length=10)),
                ('bathrooms', models.CharField(blank=True, max_length=10)),
                ('kitchen_each_floor', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('additional_rooms', models.JSONField(blank=True, null=True)),
                ('outdoor_areas', models.JSONField(blank=True, null=True)),
                ('preferred_material', models.CharField(blank=True, choices=[('bricks', 'Red Bricks'), ('aac', 'AAC Blocks'), ('fly_ash', 'Fly Ash Bricks'), ('concrete', 'Concrete Blocks'), ('not_sure', 'Not Sure')], max_length=50)),
                ('construction_style', models.CharField(blank=True, choices=[('modern', 'Modern'), ('traditional', 'Traditional'), ('contemporary', 'Contemporary'), ('minimalist', 'Minimalist'), ('not_decided', 'Not Decided')], max_length=50)),
                ('solar_panel', models.BooleanField(default=False)),
                ('design_reference', models.URLField(blank=True, null=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_contractor', to='mainapp.userinfo')),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_homeowner', to='mainapp.userinfo')),
            ],
        ),
    ]
