# Generated by Django 5.2.4 on 2025-07-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_logininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='status',
            field=models.CharField(default='active', max_length=15),
        ),
    ]
