# Generated by Django 5.2.4 on 2025-07-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_logininfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=5),
            preserve_default=False,
        ),
    ]
