# Generated by Django 5.2.4 on 2025-07-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_enquiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='date',
            new_name='enqdate',
        ),
    ]
