# Generated by Django 5.2.4 on 2025-07-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_date_enquiry_enqdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='enqdate',
        ),
    ]
