# Generated by Django 5.2.4 on 2025-08-05 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeownerapp', '0001_initial'),
        ('mainapp', '0008_alter_userinfo_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_text', models.TextField()),
                ('design_file', models.FileField(blank=True, null=True, upload_to='designs/')),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_duration', models.IntegerField(help_text='Estimated number of days')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_applications', to='mainapp.userinfo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='homeownerapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_text', models.TextField()),
                ('progress_percent', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='progress_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='homeownerapp.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.userinfo')),
            ],
        ),
    ]
